language: cpp
dist: bionic

compiler:
  -gcc
os: linux

before_install:
  - gcc -v
  - if [ $TRAVIS_OS_NAME == linux ]; then echo Running on Linux; fi

script:
  - if [ $TRAVIS_OS_NAME == linux ]; then ./configure.sh; fi

notifications:
  email: false
